"""Added admin field to clients

Revision ID: 2e1bc63e202d
Revises: 7449dc283f51
Create Date: 2020-07-02 15:11:59.362781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1bc63e202d'
down_revision = '7449dc283f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('clients', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'admin')
    # ### end Alembic commands ###
