"""Changed user id to random uuid

Revision ID: 4470c97ebf6b
Revises: c52ffb6c57d7
Create Date: 2020-06-05 22:08:43.681000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4470c97ebf6b'
down_revision = 'c52ffb6c57d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
