"""Regenerating tables with uuids

Revision ID: 5edbdb61aba9
Revises: 6f34d1f74cee
Create Date: 2020-06-05 22:39:40.250371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edbdb61aba9'
down_revision = '6f34d1f74cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
