"""Add2.0 admin field to clients

Revision ID: 665210150d76
Revises: af8aa35fd41d
Create Date: 2020-07-02 15:30:35.714293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665210150d76'
down_revision = 'af8aa35fd41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
