"""Added admin field to clients

Revision ID: 7449dc283f51
Revises: e573626bf770
Create Date: 2020-07-02 15:10:15.938769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7449dc283f51'
down_revision = 'e573626bf770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
