"""Testing working

Revision ID: 8290838af9de
Revises: 88f748a8b716
Create Date: 2020-06-05 22:22:57.785438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8290838af9de'
down_revision = '88f748a8b716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
