"""Regenerating tables with uuids 2 try

Revision ID: 8cd133bcad38
Revises: 5edbdb61aba9
Create Date: 2020-06-05 22:43:30.255339

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8cd133bcad38'
down_revision = '5edbdb61aba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('first_name', sa.String(length=60), nullable=True),
        sa.Column('last_name', sa.String(length=60), nullable=False),
        sa.Column('registration_date', sa.Date(), nullable=True),
        sa.Column('passport_number', sa.String(60), nullable=True),
        sa.Column('hashed_password', sa.String(60), nullable=True),
        sa.Column('admin', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('orders',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('id_client', sa.String(length=32), nullable=False),
                    sa.Column('id_car', sa.String(length=32), nullable=False),
                    sa.Column('add_date', sa.Date(), nullable=True),
                    sa.Column('rental_time', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_car'], ['cars.id'], ),
                    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
