"""Changed user id to random uuid

Revision ID: 9ecbd6a2bf48
Revises: 4470c97ebf6b
Create Date: 2020-06-05 22:12:20.430554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecbd6a2bf48'
down_revision = '4470c97ebf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
