"""Added admin field to clients

Revision ID: bb5ee04ac6c4
Revises: 2e1bc63e202d
Create Date: 2020-07-02 15:14:44.032313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5ee04ac6c4'
down_revision = '2e1bc63e202d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
