"""Added unique to clients passport_number

Revision ID: c52ffb6c57d7
Revises: a74dbbd98e11
Create Date: 2020-06-05 16:17:48.241928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52ffb6c57d7'
down_revision = 'a74dbbd98e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['passport_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
