"""Check working

Revision ID: f089c69e87d7
Revises: 7d37b60e4342
Create Date: 2020-06-05 11:55:49.367453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f089c69e87d7'
down_revision = '7d37b60e4342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
